# http://localhost:9090/
global:
  scrape_interval: 5s # By default, scrape targets every 5 seconds.
  evaluation_interval: 5s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'account-ingestor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert-rules.yml'

scrape_configs:
  - job_name: "account-ingestor-metrics"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: node
    static_configs:
      - targets: ["host.docker.internal:9100"]